#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/rriem/Desktop/debit SE 0.5/mainWindow.ui'
#
# Created: Fri Jul  4 21:36:25 2008
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_DebitSE(object):
    def setupUi(self, DebitSE):
        DebitSE.setObjectName("DebitSE")
        DebitSE.resize(550,400)
        self.centralwidget = QtGui.QWidget(DebitSE)
        self.centralwidget.setGeometry(QtCore.QRect(0,55,550,326))
        self.centralwidget.setObjectName("centralwidget")
        DebitSE.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(DebitSE)
        self.menubar.setGeometry(QtCore.QRect(0,0,550,21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuCalc = QtGui.QMenu(self.menubar)
        self.menuCalc.setTearOffEnabled(False)
        self.menuCalc.setObjectName("menuCalc")
        DebitSE.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(DebitSE)
        self.statusbar.setGeometry(QtCore.QRect(0,381,550,19))
        self.statusbar.setObjectName("statusbar")
        DebitSE.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(DebitSE)
        self.toolBar.setGeometry(QtCore.QRect(0,21,550,34))
        self.toolBar.setObjectName("toolBar")
        DebitSE.addToolBar(QtCore.Qt.TopToolBarArea,self.toolBar)
        self.actionAbout_Debit_SE = QtGui.QAction(DebitSE)
        self.actionAbout_Debit_SE.setVisible(True)
        self.actionAbout_Debit_SE.setMenuRole(QtGui.QAction.AboutRole)
        self.actionAbout_Debit_SE.setIconVisibleInMenu(False)
        self.actionAbout_Debit_SE.setObjectName("actionAbout_Debit_SE")
        self.actionPreferences = QtGui.QAction(DebitSE)
        self.actionPreferences.setEnabled(False)
        self.actionPreferences.setMenuRole(QtGui.QAction.PreferencesRole)
        self.actionPreferences.setIconVisibleInMenu(False)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionQuit = QtGui.QAction(DebitSE)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/quit.PNG"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon)
        self.actionQuit.setMenuRole(QtGui.QAction.QuitRole)
        self.actionQuit.setObjectName("actionQuit")
        self.actionPrint = QtGui.QAction(DebitSE)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/print.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionPrint.setIcon(icon)
        self.actionPrint.setObjectName("actionPrint")
        self.actionUndo = QtGui.QAction(DebitSE)
        self.actionUndo.setEnabled(False)
        self.actionUndo.setObjectName("actionUndo")
        self.actionCut = QtGui.QAction(DebitSE)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/cut.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionCut.setIcon(icon)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtGui.QAction(DebitSE)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/copy.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtGui.QAction(DebitSE)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/paste.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon)
        self.actionPaste.setObjectName("actionPaste")
        self.actionPatient_Data = QtGui.QAction(DebitSE)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/patient.PNG"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionPatient_Data.setIcon(icon)
        self.actionPatient_Data.setObjectName("actionPatient_Data")
        self.actionDrug_Data = QtGui.QAction(DebitSE)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/drug.PNG"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.actionDrug_Data.setIcon(icon)
        self.actionDrug_Data.setObjectName("actionDrug_Data")
        self.actionCalc = QtGui.QAction(DebitSE)
        self.actionCalc.setObjectName("actionCalc")
        self.actionExpress_Calc = QtGui.QAction(DebitSE)
        self.actionExpress_Calc.setObjectName("actionExpress_Calc")
        self.menuFile.addAction(self.actionAbout_Debit_SE)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPreferences)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuCalc.addAction(self.actionPatient_Data)
        self.menuCalc.addAction(self.actionDrug_Data)
        self.menuCalc.addSeparator()
        self.menuCalc.addAction(self.actionCalc)
        self.menuCalc.addAction(self.actionExpress_Calc)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuCalc.menuAction())
        self.toolBar.addAction(self.actionQuit)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPrint)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCut)
        self.toolBar.addAction(self.actionCopy)
        self.toolBar.addAction(self.actionPaste)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPatient_Data)
        self.toolBar.addAction(self.actionDrug_Data)
        self.toolBar.addAction(self.actionCalc)

        self.retranslateUi(DebitSE)
        QtCore.QMetaObject.connectSlotsByName(DebitSE)

    def retranslateUi(self, DebitSE):
        DebitSE.setWindowTitle(QtGui.QApplication.translate("DebitSE", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        DebitSE.setToolTip(QtGui.QApplication.translate("DebitSE", "Main Window", None, QtGui.QApplication.UnicodeUTF8))
        DebitSE.setStatusTip(QtGui.QApplication.translate("DebitSE", "Debit SE", None, QtGui.QApplication.UnicodeUTF8))
        DebitSE.setWhatsThis(QtGui.QApplication.translate("DebitSE", "This is the main window of the application", None, QtGui.QApplication.UnicodeUTF8))
        self.menubar.setStatusTip(QtGui.QApplication.translate("DebitSE", "The Menu bar", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setToolTip(QtGui.QApplication.translate("DebitSE", "File menu: print or quit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setStatusTip(QtGui.QApplication.translate("DebitSE", "File menu", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("DebitSE", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setToolTip(QtGui.QApplication.translate("DebitSE", "Edit menu", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setStatusTip(QtGui.QApplication.translate("DebitSE", "Edit menu", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("DebitSE", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCalc.setStatusTip(QtGui.QApplication.translate("DebitSE", "Calculation menu", None, QtGui.QApplication.UnicodeUTF8))
        self.menuCalc.setTitle(QtGui.QApplication.translate("DebitSE", "Calc", None, QtGui.QApplication.UnicodeUTF8))
        self.statusbar.setToolTip(QtGui.QApplication.translate("DebitSE", "This is the <i>Status bar</i> of the application.", None, QtGui.QApplication.UnicodeUTF8))
        self.statusbar.setWhatsThis(QtGui.QApplication.translate("DebitSE", "This is the <i>Status bar</i> of the application", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("DebitSE", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Debit_SE.setText(QtGui.QApplication.translate("DebitSE", "About Debit SE...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setText(QtGui.QApplication.translate("DebitSE", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("DebitSE", "Quit ", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setStatusTip(QtGui.QApplication.translate("DebitSE", "Quit Debit SE", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setShortcut(QtGui.QApplication.translate("DebitSE", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setText(QtGui.QApplication.translate("DebitSE", "Print...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setToolTip(QtGui.QApplication.translate("DebitSE", "Open the <i>Print diaglog...</i>", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setStatusTip(QtGui.QApplication.translate("DebitSE", "Print dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrint.setShortcut(QtGui.QApplication.translate("DebitSE", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setText(QtGui.QApplication.translate("DebitSE", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setStatusTip(QtGui.QApplication.translate("DebitSE", "Undo the last action.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setShortcut(QtGui.QApplication.translate("DebitSE", "Ctrl+Z", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setText(QtGui.QApplication.translate("DebitSE", "Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setStatusTip(QtGui.QApplication.translate("DebitSE", "Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setShortcut(QtGui.QApplication.translate("DebitSE", "Ctrl+X", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("DebitSE", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setStatusTip(QtGui.QApplication.translate("DebitSE", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setShortcut(QtGui.QApplication.translate("DebitSE", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setText(QtGui.QApplication.translate("DebitSE", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setStatusTip(QtGui.QApplication.translate("DebitSE", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setShortcut(QtGui.QApplication.translate("DebitSE", "Ctrl+V", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPatient_Data.setText(QtGui.QApplication.translate("DebitSE", "Patient Data", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDrug_Data.setText(QtGui.QApplication.translate("DebitSE", "Drug Data", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCalc.setText(QtGui.QApplication.translate("DebitSE", "Calc", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExpress_Calc.setText(QtGui.QApplication.translate("DebitSE", "Express Calc", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    DebitSE = QtGui.QMainWindow()
    ui = Ui_DebitSE()
    ui.setupUi(DebitSE)
    DebitSE.show()
    sys.exit(app.exec_())

