"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from distutils.core import setup
import py2app
import os
os.system("/bin/rm -rf dist")
os.system("/bin/rm -rf build")
os.system("/bin/rm -rf *.pyc")


APP = ['debit.py']
DATA_FILES = ['ressources.py', 'fenetre.py']
OPTIONS = {'argv_emulation': True, 'iconfile': '/Users/rriem/Desktop/sources/debit.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
