# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calcExpress.ui'
#
# Created: Sun Mar  8 13:08:52 2009
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(571,243)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed,QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/calculator2.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(True)
        self.frame_2 = QtGui.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(430,20,111,201))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton = QtGui.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(10,10,81,32))
        self.pushButton.setAutoDefault(True)
        self.pushButton.setDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.buttonBox = QtGui.QDialogButtonBox(self.frame_2)
        self.buttonBox.setGeometry(QtCore.QRect(10,160,81,31))
        self.buttonBox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.frame_1 = QtGui.QFrame(Dialog)
        self.frame_1.setGeometry(QtCore.QRect(10,20,401,201))
        self.frame_1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.comboBox_unitConcentration = QtGui.QComboBox(self.frame_1)
        self.comboBox_unitConcentration.setGeometry(QtCore.QRect(230,10,102,26))
        self.comboBox_unitConcentration.setObjectName("comboBox_unitConcentration")
        self.label_concentration = QtGui.QLabel(self.frame_1)
        self.label_concentration.setGeometry(QtCore.QRect(11,12,101,22))
        self.label_concentration.setObjectName("label_concentration")
        self.lineEdit_Conc = QtGui.QLineEdit(self.frame_1)
        self.lineEdit_Conc.setGeometry(QtCore.QRect(120,12,91,22))
        self.lineEdit_Conc.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit_Conc.setMaxLength(6)
        self.lineEdit_Conc.setObjectName("lineEdit_Conc")
        self.label_Weight = QtGui.QLabel(self.frame_1)
        self.label_Weight.setGeometry(QtCore.QRect(20,50,51,17))
        self.label_Weight.setObjectName("label_Weight")
        self.lineEdit_Weight = QtGui.QLineEdit(self.frame_1)
        self.lineEdit_Weight.setGeometry(QtCore.QRect(120,50,91,22))
        self.lineEdit_Weight.setObjectName("lineEdit_Weight")
        self.label_unitWeight = QtGui.QLabel(self.frame_1)
        self.label_unitWeight.setGeometry(QtCore.QRect(230,50,61,17))
        self.label_unitWeight.setObjectName("label_unitWeight")
        self.label_Poso = QtGui.QLabel(self.frame_1)
        self.label_Poso.setGeometry(QtCore.QRect(20,100,81,17))
        self.label_Poso.setObjectName("label_Poso")
        self.lineEdit_Poso = QtGui.QLineEdit(self.frame_1)
        self.lineEdit_Poso.setGeometry(QtCore.QRect(120,100,91,22))
        self.lineEdit_Poso.setObjectName("lineEdit_Poso")
        self.comboBox_Poso = QtGui.QComboBox(self.frame_1)
        self.comboBox_Poso.setGeometry(QtCore.QRect(230,100,131,26))
        self.comboBox_Poso.setObjectName("comboBox_Poso")
        self.label_Flow = QtGui.QLabel(self.frame_1)
        self.label_Flow.setGeometry(QtCore.QRect(20,150,61,17))
        self.label_Flow.setObjectName("label_Flow")
        self.lineEdit_Flow = QtGui.QLineEdit(self.frame_1)
        self.lineEdit_Flow.setGeometry(QtCore.QRect(120,150,71,22))
        self.lineEdit_Flow.setObjectName("lineEdit_Flow")
        self.label_unitFlow = QtGui.QLabel(self.frame_1)
        self.label_unitFlow.setGeometry(QtCore.QRect(230,150,61,17))
        self.label_unitFlow.setObjectName("label_unitFlow")
        self.label_concentration.setBuddy(self.lineEdit_Conc)
        self.label_Weight.setBuddy(self.lineEdit_Weight)
        self.label_Poso.setBuddy(self.lineEdit_Poso)
        self.label_Flow.setBuddy(self.lineEdit_Flow)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox,QtCore.SIGNAL("accepted()"),Dialog.accept)
        QtCore.QObject.connect(self.buttonBox,QtCore.SIGNAL("rejected()"),Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEdit_Conc,self.comboBox_unitConcentration)
        Dialog.setTabOrder(self.comboBox_unitConcentration,self.lineEdit_Weight)
        Dialog.setTabOrder(self.lineEdit_Weight,self.lineEdit_Poso)
        Dialog.setTabOrder(self.lineEdit_Poso,self.comboBox_Poso)
        Dialog.setTabOrder(self.comboBox_Poso,self.lineEdit_Flow)
        Dialog.setTabOrder(self.lineEdit_Flow,self.pushButton)
        Dialog.setTabOrder(self.pushButton,self.buttonBox)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Calcul Express", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Dialog", "Calculer", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_unitConcentration.addItem(QtGui.QApplication.translate("Dialog", "µg / ml", None, QtGui.QApplication.UnicodeUTF8))
        self.label_concentration.setText(QtGui.QApplication.translate("Dialog", "Concentration : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Weight.setText(QtGui.QApplication.translate("Dialog", "Poids : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_unitWeight.setText(QtGui.QApplication.translate("Dialog", "Kg", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Poso.setText(QtGui.QApplication.translate("Dialog", "Posologie : ", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_Poso.addItem(QtGui.QApplication.translate("Dialog", "µg / Kg / min", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Flow.setText(QtGui.QApplication.translate("Dialog", "Débit : ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_unitFlow.setText(QtGui.QApplication.translate("Dialog", "ml / h", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

